version: '3.4'

services:
  moviesapi:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: moviesAPI/Dockerfile
    depends_on:
      - sqlserverService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:5000"
  sqlserverService:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:latest
    hostname: movieDb
    container_name: movieDb
    environment:
      ACCEPT_EULA: Y
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - 5050:1433

