version: '3.4'

services:
  moviesapi:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: moviesAPI/Dockerfile
    depends_on:
      - sqlserverService
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    networks:
      - my-network
  sqlserverService:
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:latest
    hostname: movieDb
    container_name: movieDb
    environment:
      ACCEPT_EULA: Y
    volumes:
      - ./data/mssql:/var/opt/mssql3
    ports:
      - 1433:1433
    networks:
      - my-network
networks:
  my-network:
    external: true
    driver: bridge

